# Generated by Django 5.1.7 on 2025-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
